### ISSUE TITLE
int32 causes: binary.push(packer[s + byteord](obj[el])); when packing

### ISSUE THREAD

**Issue by alexmk92** [majimboo/c-struct#4]
I just found this module, it looks like it's going to save me a substantial amount of time, I'm trying to send buffers to the other end of a TCP connection and it requires one field to be a 32 bit integer. 

When I use the `int32` type I get the error:

`/Users/alexsims/Koda/clients/datacom/SubscriberApp/node_modules/c-struct/lib/cstruct.js:166
            binary.push(packer[s + byteord](obj[el]));
`

On line 166 inside of `cstruct.js`.  If I swap the int32 declaration for a uint32 the error disappears.  Any ideas what's going on here? I'm using node 6.5.0 right now.

**Comment by majimboo** [comment]
This is because this module only supports unsigned integers. I haven't added support for signed. I also have not updated this in a long time. I suggest, ByteBufferJS.
